"""PDF generation for attendance reports using ReportLab."""

import io
from datetime import datetime
from reportlab.lib import colors
from reportlab.lib.pagesizes import A4
from reportlab.lib.units import mm
from reportlab.platypus import SimpleDocTemplate, Table, TableStyle, Paragraph, Spacer, PageBreak
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
from reportlab.lib.enums import TA_CENTER, TA_LEFT, TA_RIGHT

from app.config import get_settings


async def generate_attendance_pdf(db, report_type: str, **kwargs) -> io.BytesIO:
    """Generate a PDF report and return as BytesIO stream."""
    buffer = io.BytesIO()
    doc = SimpleDocTemplate(buffer, pagesize=A4, topMargin=20*mm, bottomMargin=20*mm,
                            leftMargin=15*mm, rightMargin=15*mm)
    styles = getSampleStyleSheet()
    settings = get_settings()

    title_style = ParagraphStyle('CustomTitle', parent=styles['Heading1'], fontSize=16,
                                  alignment=TA_CENTER, spaceAfter=6)
    subtitle_style = ParagraphStyle('CustomSubtitle', parent=styles['Heading2'], fontSize=11,
                                     alignment=TA_CENTER, spaceAfter=12, textColor=colors.grey)
    footer_style = ParagraphStyle('Footer', parent=styles['Normal'], fontSize=7,
                                   alignment=TA_CENTER, textColor=colors.grey)

    elements = []

    if report_type == "class_daily":
        elements = await _class_daily(db, styles, title_style, subtitle_style, settings, **kwargs)
    elif report_type == "class_monthly":
        elements = await _class_monthly(db, styles, title_style, subtitle_style, settings, **kwargs)
    elif report_type == "class_annual":
        elements = await _class_annual(db, styles, title_style, subtitle_style, settings, **kwargs)
    elif report_type == "school_daily":
        elements = await _school_daily(db, styles, title_style, subtitle_style, settings, **kwargs)
    elif report_type == "school_monthly":
        elements = await _school_monthly(db, styles, title_style, subtitle_style, settings, **kwargs)
    elif report_type == "school_annual":
        elements = await _school_annual(db, styles, title_style, subtitle_style, settings, **kwargs)

    elements.append(Spacer(1, 10*mm))
    elements.append(Paragraph(f"Generated by {settings.pdf_school_name} Management System", footer_style))

    doc.build(elements)
    buffer.seek(0)
    return buffer


def _header_elements(settings, title_style, subtitle_style, title, subtitle):
    return [
        Paragraph(settings.pdf_school_name, title_style),
        Paragraph(title, subtitle_style),
        Paragraph(subtitle, ParagraphStyle('Sub2', fontSize=9, alignment=TA_CENTER, textColor=colors.grey)),
        Spacer(1, 8*mm),
    ]


def _make_table(headers, data_rows, col_widths=None):
    table_data = [headers] + data_rows
    t = Table(table_data, colWidths=col_widths, repeatRows=1)
    t.setStyle(TableStyle([
        ('BACKGROUND', (0, 0), (-1, 0), colors.HexColor('#059669')),
        ('TEXTCOLOR', (0, 0), (-1, 0), colors.white),
        ('FONTSIZE', (0, 0), (-1, 0), 9),
        ('FONTNAME', (0, 0), (-1, 0), 'Helvetica-Bold'),
        ('FONTSIZE', (0, 1), (-1, -1), 8),
        ('ALIGN', (0, 0), (-1, -1), 'CENTER'),
        ('ALIGN', (1, 1), (1, -1), 'LEFT'),
        ('GRID', (0, 0), (-1, -1), 0.5, colors.grey),
        ('ROWBACKGROUNDS', (0, 1), (-1, -1), [colors.white, colors.HexColor('#f8fafc')]),
        ('VALIGN', (0, 0), (-1, -1), 'MIDDLE'),
        ('TOPPADDING', (0, 0), (-1, -1), 4),
        ('BOTTOMPADDING', (0, 0), (-1, -1), 4),
    ]))
    return t


async def _get_class_name(db, class_id):
    r = await db.fetchrow("SELECT grade, medium, gender_type FROM classes WHERE id = $1", class_id)
    return f"Grade {r['grade']} {r['medium']} {r['gender_type']}" if r else "Unknown"


async def _class_daily(db, styles, title_style, subtitle_style, settings, class_id, date, **_):
    class_name = await _get_class_name(db, class_id)
    elements = _header_elements(settings, title_style, subtitle_style,
                                 f"Daily Attendance Report", f"{class_name} — {date}")
    rows = await db.fetch(
        """SELECT s.registration_number, s.full_name, s.gender, a.status
           FROM attendance a JOIN students s ON a.student_id = s.id
           WHERE a.class_id = $1 AND a.attendance_date = $2
           ORDER BY s.full_name""", class_id, date)

    data = [[r["registration_number"], r["full_name"], r["gender"], r["status"]] for r in rows]
    present = sum(1 for r in rows if r["status"] == "Present")
    absent = len(rows) - present
    pct = round((present / len(rows)) * 100, 1) if rows else 0

    elements.append(_make_table(["Reg No.", "Student Name", "Gender", "Status"], data,
                                 col_widths=[35*mm, 70*mm, 25*mm, 25*mm]))
    elements.append(Spacer(1, 5*mm))
    summary = [[f"Present: {present}", f"Absent: {absent}", f"Attendance: {pct}%"]]
    elements.append(_make_table(["Present", "Absent", "Attendance %"], summary))
    return elements


async def _class_monthly(db, styles, title_style, subtitle_style, settings, class_id, month, year, **_):
    class_name = await _get_class_name(db, class_id)
    month_name = datetime(year, month, 1).strftime('%B %Y')
    elements = _header_elements(settings, title_style, subtitle_style,
                                 f"Monthly Attendance Report", f"{class_name} — {month_name}")

    sundays = await db.fetch(
        """SELECT DISTINCT attendance_date FROM attendance
           WHERE class_id = $1 AND EXTRACT(MONTH FROM attendance_date) = $2
           AND EXTRACT(YEAR FROM attendance_date) = $3 ORDER BY attendance_date""",
        class_id, month, year)

    students = await db.fetch(
        """SELECT DISTINCT s.id, s.registration_number, s.full_name, s.gender
           FROM attendance a JOIN students s ON a.student_id = s.id
           WHERE a.class_id = $1 AND EXTRACT(MONTH FROM a.attendance_date) = $2
           AND EXTRACT(YEAR FROM a.attendance_date) = $3 ORDER BY s.full_name""",
        class_id, month, year)

    headers = ["Reg No.", "Name", "Gender"] + [str(s["attendance_date"].day) for s in sundays] + ["Total P", "%"]
    data = []
    for st in students:
        row = [st["registration_number"], st["full_name"], st["gender"]]
        total_p = 0
        for sun in sundays:
            att = await db.fetchval(
                "SELECT status FROM attendance WHERE student_id = $1 AND attendance_date = $2",
                st["id"], sun["attendance_date"])
            row.append("P" if att == "Present" else "A")
            if att == "Present":
                total_p += 1
        pct = round((total_p / len(sundays)) * 100) if sundays else 0
        row.extend([str(total_p), f"{pct}%"])
        data.append(row)

    if data:
        elements.append(_make_table(headers, data))
    else:
        elements.append(Paragraph("No attendance records for this period.", styles['Normal']))
    return elements


async def _class_annual(db, styles, title_style, subtitle_style, settings, class_id, academic_year_id, **_):
    class_name = await _get_class_name(db, class_id)
    year_label = await db.fetchval("SELECT year_label FROM academic_years WHERE id = $1", academic_year_id)
    elements = _header_elements(settings, title_style, subtitle_style,
                                 f"Annual Attendance Report", f"{class_name} — {year_label}")

    students = await db.fetch(
        """SELECT DISTINCT s.id, s.registration_number, s.full_name, s.gender
           FROM attendance a JOIN students s ON a.student_id = s.id
           WHERE a.class_id = $1 ORDER BY s.full_name""", class_id)

    data = []
    for st in students:
        stats = await db.fetchrow(
            """SELECT COUNT(*) AS total,
                      COUNT(*) FILTER (WHERE status = 'Present') AS present
               FROM attendance WHERE student_id = $1 AND class_id = $2""",
            st["id"], class_id)
        pct = round((stats["present"] / stats["total"]) * 100) if stats["total"] else 0
        data.append([st["registration_number"], st["full_name"], st["gender"],
                     str(stats["present"]), str(stats["total"] - stats["present"]), f"{pct}%"])

    elements.append(_make_table(["Reg No.", "Name", "Gender", "Present", "Absent", "%"], data))
    return elements


async def _school_daily(db, styles, title_style, subtitle_style, settings, date, **_):
    elements = _header_elements(settings, title_style, subtitle_style,
                                 f"School Daily Attendance Report", date)
    classes = await db.fetch(
        """SELECT DISTINCT a.class_id, c.grade, c.medium, c.gender_type
           FROM attendance a JOIN classes c ON a.class_id = c.id
           WHERE a.attendance_date = $1 ORDER BY c.medium, c.grade""", date)

    data = []
    for cls in classes:
        name = f"Grade {cls['grade']} {cls['medium']} {cls['gender_type']}"
        stats = await db.fetchrow(
            """SELECT COUNT(*) AS total, COUNT(*) FILTER (WHERE status = 'Present') AS present
               FROM attendance WHERE class_id = $1 AND attendance_date = $2""",
            cls["class_id"], date)
        absent = stats["total"] - stats["present"]
        pct = round((stats["present"] / stats["total"]) * 100) if stats["total"] else 0
        data.append([name, str(stats["present"]), str(absent), f"{pct}%"])

    elements.append(_make_table(["Class", "Present", "Absent", "%"], data))
    return elements


async def _school_monthly(db, styles, title_style, subtitle_style, settings, month, year, **_):
    month_name = datetime(year, month, 1).strftime('%B %Y')
    elements = _header_elements(settings, title_style, subtitle_style,
                                 f"School Monthly Attendance Report", month_name)
    classes = await db.fetch(
        """SELECT DISTINCT a.class_id, c.grade, c.medium, c.gender_type
           FROM attendance a JOIN classes c ON a.class_id = c.id
           WHERE EXTRACT(MONTH FROM a.attendance_date) = $1 AND EXTRACT(YEAR FROM a.attendance_date) = $2
           ORDER BY c.medium, c.grade""", month, year)

    data = []
    for cls in classes:
        name = f"Grade {cls['grade']} {cls['medium']} {cls['gender_type']}"
        stats = await db.fetchrow(
            """SELECT COUNT(*) AS total, COUNT(*) FILTER (WHERE status = 'Present') AS present
               FROM attendance WHERE class_id = $1 AND EXTRACT(MONTH FROM attendance_date) = $2
               AND EXTRACT(YEAR FROM attendance_date) = $3""",
            cls["class_id"], month, year)
        absent = stats["total"] - stats["present"]
        pct = round((stats["present"] / stats["total"]) * 100) if stats["total"] else 0
        data.append([name, str(stats["present"]), str(absent), f"{pct}%"])

    elements.append(_make_table(["Class", "Present", "Absent", "%"], data))
    return elements


async def _school_annual(db, styles, title_style, subtitle_style, settings, academic_year_id, **_):
    year_label = await db.fetchval("SELECT year_label FROM academic_years WHERE id = $1", academic_year_id)
    elements = _header_elements(settings, title_style, subtitle_style,
                                 f"School Annual Attendance Report", f"Academic Year {year_label}")
    classes = await db.fetch(
        """SELECT c.id, c.grade, c.medium, c.gender_type FROM classes c
           WHERE c.academic_year_id = $1 ORDER BY c.medium, c.grade""", academic_year_id)

    data = []
    for cls in classes:
        name = f"Grade {cls['grade']} {cls['medium']} {cls['gender_type']}"
        stats = await db.fetchrow(
            """SELECT COUNT(*) AS total, COUNT(*) FILTER (WHERE status = 'Present') AS present
               FROM attendance WHERE class_id = $1""", cls["id"])
        absent = (stats["total"] or 0) - (stats["present"] or 0)
        pct = round((stats["present"] / stats["total"]) * 100) if stats["total"] else 0
        data.append([name, str(stats["present"] or 0), str(absent), f"{pct}%"])

    elements.append(_make_table(["Class", "Present", "Absent", "%"], data))
    return elements
